blog/urls.py
from django.urls import path
from blog import views

app_name = "blog"


urlpatterns = [
    path('', views.home_view, name='home'),
    path('rating/', views.rating_view, name='rating'),
    path('post/<slug:slug>/', views.post_detail_view, name='post_detail'),
    path('casino/<slug:casino>/', views.casino_detail_view, name='casino_detail'),

    # AJAX Endpoints
    path('post/<slug:slug>/like/', views.post_like, name='post_like'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500, handler403, handler400

from blog import views

admin.site.site_header = 'Awesome Inc. Administration'
admin.site.site_title = 'Awesome Inc. Administration'


handler400 = 'blog.views.error400'
handler403 = 'blog.views.error403'
handler404 = 'blog.views.error404'
handler500 = 'blog.views.error500'


urlpatterns = [
    path('secret/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    path('summernote/', include('django_summernote.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

casinos/models.py
import datetime

from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.conf import settings

from autoslug import AutoSlugField


# Rating Exceptions 
# User already rated the casino
class UserExists(Exception):
    pass

# Casino was already rated by the ip address
class IpExists(Exception):
    pass


def current_year():
    return datetime.date.today().year

def max_value_current_year(value):
    return MaxValueValidator(current_year())(value)


class Feature(models.Model):
    NEUTRAL = 'NEUTRAL'
    PROS = 'PROS'
    CONS = 'CONS'

    POLE_CHOICES = (
        (NEUTRAL, 'NEUTRAL'),
        (PROS, 'PROS'),
        (CONS, 'CONS'),
    )

    name = models.CharField(max_length=100)
    pole = models.CharField(max_length=20, choices=POLE_CHOICES, default=NEUTRAL)

    def __str__(self):
        return f'{self.pole} - {self.name}'


class CasinoDetail(models.Model):
    ca_license = models.CharField(max_length=100, default="Нет", \
        blank=True, null=True, verbose_name="License")
    ca_license_bool = models.BooleanField(max_length=100, default=False, \
        verbose_name="License")

    # Banned countries
    banned_countries = models.TextField(blank = True,
        verbose_name="Banned players from")

    dol = models.PositiveIntegerField(default=current_year(),
        validators=[MinValueValidator(1984), max_value_current_year],
        verbose_name="Date of launching")

    crypto = models.BooleanField(default=False, verbose_name="Cryptocasino?")
    scam = models.BooleanField(default=False, verbose_name="Scam?")
    script = models.BooleanField(default=False, verbose_name="Script?")

    feature = models.ManyToManyField(Feature, related_name='features')

    # Content
    short_desc = models.TextField(max_length = 1024, blank = True,\
        verbose_name="Short description")
    content = models.TextField(blank = True, verbose_name="Content")

    # Jackpot
    jackpot_bool = models.BooleanField(default=False, verbose_name="Jackpot Y/N")
    jackpot = models.CharField(max_length=20, blank=True, null=True, verbose_name="Jackpot value" )
    jackpot_value = models.SmallIntegerField(blank=True, null=True, verbose_name="Jackpot value in digits($)")

    # Withdrawal
    min_in = models.CharField(max_length=1024, blank=True, verbose_name="Min limit/deposit" )
    min_output = models.CharField(max_length=1024, blank=True, verbose_name="Min Output" )
    max_output = models.CharField(max_length=1024, blank=True, verbose_name="Max Output" )
    
    # Withdrawal docs
    with_docs_bool = models.BooleanField(default=True, verbose_name="Casino wants docs to withdrawal?")
    with_easy = models.CharField(max_length=50, verbose_name="How easy to withdrawal?")
    with_freq = models.CharField(max_length=1024, blank=True, verbose_name="Witdrawal frequency(d,w)" )

    # Cashback
    cashback = models.CharField(max_length=50, blank=True, null=True,\
        verbose_name="Cashback value")
    cashback_bool = models.BooleanField(default=False, verbose_name="Cashback Y/N")

    # Customer support
    support_grade = models.DecimalField (max_digits = 3, decimal_places=1,\
        default=0, verbose_name="Customer support grade")
    support_desc = models.CharField(max_length=1024, verbose_name="Support grade")
    rus_support = models.BooleanField(default=False, verbose_name="Russian support?")

    class Meta:
        abstract = True


class Casino(CasinoDetail):
    title = models.CharField(max_length=100, verbose_name="Name")
    slug = AutoSlugField(populate_from='title')
    image = models.ImageField(upload_to="casino_logos/")
    link = models.URLField(max_length=300, blank=True, verbose_name="Affiliate link")

    def __str__(self):
        return self.title
    
    # Is an instance marked as a 'top casino'
    def is_top(self):
        if TopCasino.objects.filter(casino=self).exists():
            return True
        return False
    
    # Features 
    def get_neutral(self):
        return self.feature.filter(pole=Feature.NEUTRAL)

    def get_pros(self):
        return self.feature.filter(pole=Feature.PROS)

    def get_cons(self):
        return self.feature.filter(pole=Feature.CONS)

    # Rating
    @property
    def get_rates(self):
        return CasinoRating.objects.filter(casino=self)        

    def get_rating_count(self):
        return CasinoRating.objects.filter(casino=self).count()

    def get_avg_main_rate(self):
        return float(CasinoRating.objects.filter(casino=self).aggregate(models.Avg('rate'))['rate__avg'])
    def get_avg_safe_rate(self):
        return float(CasinoRating.objects.filter(casino=self).aggregate(models.Avg('rate_safe'))['rate_safe__avg'])
    def get_avg_faith_rate(self):
        return float(CasinoRating.objects.filter(casino=self).aggregate(models.Avg('rate_faith'))['rate_faith__avg'])
    def get_avg_soft_rate(self):
        return float(CasinoRating.objects.filter(casino=self).aggregate(models.Avg('rate_soft'))['rate_soft__avg'])
    def get_avg_design_rate(self):
        return float(CasinoRating.objects.filter(casino=self).aggregate(models.Avg('rate_design'))['rate_design__avg'])

    # Get payments
    def get_payments(self):
        return self.payment_set.all()
    
    # Get bonuses
    def get_bonuses(self):
        return self.bonus_set.all()
    
    # Get software
    def get_soft(self):
        return self.software_set.all()

    ## Get license
    # def get_license(self):
        # pass

    # Does accept cryptocurrency as a payment gateway
    def does_accept_crypto(self):
        # If it accepts btc - it accepts crypto
        if self.payment_set.filter(name="Bitcoin"):
            return True
        return False


class CasinoRating(models.Model):
    rate = models.DecimalField(max_digits=3, decimal_places=1, default=0,
        verbose_name="Main rate")

    rate_soft = models.DecimalField(max_digits=3, decimal_places=1,
        default=0, verbose_name="Software Rate")
    rate_design = models.DecimalField(max_digits=3, decimal_places=1,
        default=0, verbose_name="Design Rate")
    rate_safe = models.DecimalField(max_digits=3, decimal_places=1,
        default=0, verbose_name="Safe Rate")
    rate_faith = models.DecimalField(max_digits=3, decimal_places=1,
        default=0, verbose_name="Faith Rate")

    user = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True,
        on_delete=models.SET_NULL)

    ip = models.GenericIPAddressField(blank=True, null=True)
    casino = models.ForeignKey(Casino, on_delete=models.CASCADE)

    class Meta:
        # unique_together = [['casino', 'user'], ['casino', 'ip']]
        verbose_name_plural = 'Casino Ratings'

    def __str__(self):
        return f'{self.rate} - {self.casino.title}'

    def save(self, *args, **kwargs):
        # Logged In
        if self.user:
            # Checks if 
            user_ratings = CasinoRating.objects.filter(casino=self.casino).filter(user=self.user)
            if user_ratings.exists():
                raise UserExists('You have already rated this casino')
            else:
                super(CasinoRating, self).save(*args, **kwargs)
        # Anonymous User 
        else:
            ip_ratings = CasinoRating.objects.filter(casino=self.casino).filter(ip=self.ip)
            if ip_ratings.exists():
                raise IpExists('Casino was already rated by this IP')
            else:
                super(CasinoRating, self).save(*args, **kwargs)


class TopCasino(models.Model):
    casino = models.OneToOneField(Casino, on_delete=models.CASCADE)
    sponsored = models.BooleanField(default=False)

    class Meta:
        ordering = ['sponsored', 'casino']

    def __str__(self):
        return f'[S:{self.sponsored}]- {self.casino.title}'    

    @classmethod
    def get_top_casinos(cls, self):
        pass


class Bonus(models.Model):
    two_word_desc = models.CharField(max_length= 300, default="No bonuses")    
    bonus_digit = models.PositiveSmallIntegerField(verbose_name="Bonus value")
    bonus_desc = models.TextField(blank=True, verbose_name="Bonus Description")

    casino = models.ManyToManyField(Casino)

    dep_bool = models.BooleanField(default=True, blank=False)
    dep = models.PositiveSmallIntegerField(blank = False)

    class Meta:
        ordering = ['-bonus_digit']

    def __str__(self):
        return self.two_word_desc


class Payment(models.Model):
    name = models.CharField(max_length=100, unique=True)
    image = models.ImageField(upload_to='payment_logos/', blank=True, null=True)

    is_crypto = models.BooleanField(default=False, verbose_name="Is it crypto ?")
    casino = models.ManyToManyField(Casino, blank=True, null=True)


class Software(models.Model):
    name = models.CharField(max_length=100, unique=True) 
    description = models.TextField(max_length=1024, blank=True, null=True)
    casino = models.ManyToManyField(Casino, blank=True, null=True)
    icon = models.ImageField(upload_to="software_icons/", blank=True, null=True)


class Game(models.Model):
    name = models.CharField(max_length=100, unique=True) 
    description = models.TextField(max_length=1024, blank=True, null=True)
    casino = models.ManyToManyField(Casino, blank=True, null=True)
    icon = models.ImageField(upload_to="software_icons/", blank=True, null=True)


# class License(models.Model):
#     name = models.CharField(max_length=100, default="Отсутствует", unique=True, blank=False) 
#     description = models.TextField(blank = True, verbose_name="License's description")
#     casino = models.ForeignKey(Casino, on_delete=models.SET_NULL, blank=True, null=True)

casinos/views.py
from django.shortcuts import render

# Create your views here.

templates/base.html
<!DOCTYPE html>
<html>

<head>
    <title>{% block title %}Gambling Web Application For Reviews And
        Rating{% endblock title %}</title>

    <!-- Meta -->
    <meta name="google" content="notranslate" />
    <meta charset="utf-8">
    <meta name="viewport"
        content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="This is an awesome website" />

    {% load static %}

    <!-- Icon -->
    <link rel="icon" href="{% static 'img/suit.svg' %}">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700"
        rel="stylesheet">
    <link
        href="https://fonts.googleapis.com/css?family=Ubuntu:400,700&display=swap&subset=cyrillic"
        rel="stylesheet">

    <!-- Awesome Fonts -->
    <script src="https://kit.fontawesome.com/c14d216d96.js"
        crossorigin="anonymous"></script>

    <!-- Bootstrap -->
    <link rel="stylesheet"
        href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
        crossorigin="anonymous" />
    <!-- Overhang -->
    <link rel="stylesheet" href="{% static 'css/overhang.min.css' %}">

    <!-- Styles -->
    <link rel="stylesheet" href="{% static 'scss/base.css' %}">
    <link rel="stylesheet" href="{% static 'scss/social-buttons.css' %}">

    {% block extra_css %}
    {% endblock extra_css %}

</head>

<body>
    <!-- Nav -->

    <!-- Logo -->
    <div class='logo-block'>
        <a href="{% url 'blog:home' %}">
            <img id="logo" src="{% static 'img/poker-chip.svg' %}" alt="logo">
        </a>
    </div>

    <!-- Navbar -->
    <nav class="navbar navbar-expand-sm justify-content-center">

        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link text-black font-weight-bold"
                    href="{% url 'blog:rating' %}">
                    Casino rating</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-black font-weight-bold"
                    href="{% url 'blog:home' %}#fresh-posts">
                    Blog</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-black font-weight-bold" href="#">
                    Get free bonuses</a>
            </li>
        </ul>
    </nav>
    <!--  -->

    {% block adv_block %}{% endblock adv_block %}
    {% block content %}{% endblock content %}

    <!-- Footer -->
    <footer>
        <img src="{% static 'img/18+.png' %}" alt="18+">

        <!-- Social Buttons -->
        <div class="social-buttons">
            <!-- facebook  Button -->
            <a href="http://www.facebook.com" target="blank"
                class="social-margin">
                <div class="social-icon facebook">
                    <i class="fab fa-facebook-f"></i>
                </div>
            </a>
            <!-- pinterest Button -->
            <a href="https://pinterest.com/" target="blank"
                class="social-margin">
                <div class="social-icon pinterest">
                    <i class="fab fa-pinterest-p"></i>
                </div>
            </a>
            <!-- Youtube Button -->
            <a href="http://youtube.com/" target="blank" class="social-margin">
                <div class="social-icon youtube">
                    <i class="fab fa-youtube"></i>
                </div>
            </a>

            <!-- TwitterButton -->
            <a href="http://twitter.com/" target="blank" class="social-margin">
                <div class="social-icon twitter">
                    <i class="fab fa-twitter"></i>
                </div>
            </a>
        </div>
        <!-- /Social Buttons -->
        <p>
            The site is exclusively informative in nature, does not organize and
            conduct gambling. We do not engage in propaganda and do not force
            visitors to the site for real money. All materials collected on the
            site are intellectual property. Any copying without
            reference to the source is prohibited.
        </p>
        <p>Copyright 2020 Only Gambling Ltd.</p>
    </footer>




    <!-- JQuery, Popper, Bootstrap, Underscore -->
    <!-- <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script> -->
    <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/jquery-ui.min.js"></script>
    <script
        src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script
        src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
    <!-- Overhang -->
    <script src="{% static 'js/overhang.min.js' %}"></script>
    <!-- Notifications -->
    <script>
        {% if messages %}
            {% for message in messages %}
                $("body").overhang({
                    type: "{{ message.tags }}",
                    duration: 5,
                    message: "{{ message }}",
                    closeConfirm: true,
                });

            {% endfor %}
        {% endif %}
    </script>

{% block extra_js %}
{% endblock extra_js %}
</body>


</html>

templates/comments.html
<div id="disqus_thread"></div>

<script>
    // Change only the variables below    
    // let PAGE_URL = "https://yourdomain.in/post/{{ slug }}/";
    let PAGE_URL = "https://localhost:8000/post/{{ slug }}/";
    let PAGE_IDENTIFIER = '{{ slug }}';


    var disqus_config = function () {
        this.page.url = PAGE_URL;
        this.page.identifier = PAGE_IDENTIFIER;
    };

    (function () { // DON'T EDIT BELOW THIS LINE
        var d = document,
            s = d.createElement('script');
        s.src = 'https://bestcasinos-1.disqus.com/embed.js';
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
    })();
</script>
<noscript>Please enable JavaScript to view the <a
        href="https://disqus.com/?ref_noscript">comments powered by
        Disqus.</a></noscript>

templates/index.html
{% extends "base.html" %}
{% load static %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock extra_css %}

{% block content %}
<div class="jumbotron">
    <!-- Pin Up Girl -->
    <img id="jumbotron-image" src="{% static 'img/pinup_girl.png' %}"
        alt="Pin Up Girl">

    <div class="container">
        <h1 class="display-4 text-center jumbotron-title">Best casinos in 2019
        </h1>
        <p class="lead">
            Thanks to the online casinos, it is possible to play whenever and
            wherever you like by using your computer, smartphone or tablet.
            Since most online casinos also offer a user-friendly mobile platform
            that is fully compatible with various mobile devices, it is even
            possible to play on the move. Gambling online can be a great
            experience as long as you play in only reputable online casinos. It
            is essential to manage to choose the best online casino as your
            gaming experience greatly depends on it.
        </p>

        <hr class="my-4">

        <p>
            Playing casino games online can be a truly fabulous experience. It’s
            better when you win, of course, but it can still be fun even when
            you lose. It’s important, if not essential, that you use the best
            online casinos when playing for real money.
        </p>

        <p class="lead">
            <a class="btn btn-success btn-lg header-rating-button">See our list
                of TOP rated casinos</a>
        </p>
    </div>
</div>

<!-- Main -->
<main>
    <div class="container">
        <div class="row">
            <div class="col-md-8 mt-3 left">
                <a name="fresh-posts" href=""></a>
                <h2 id="listing-heading">New Posts</h2>

                {% for post in posts %}
                <div class="card mb-4">
                    <div class="card-body">
                        <h2 class="card-title">{{ post.title }}</h2>

                        <p class="card-text text-muted h6">
                            {{ post.created|date:'d/m/Y H:i' }} </p>
                        <p class="card-text">
                            {{post.content|truncatechars_html:300|safe }}</p>

                        <div class="card-down">
                            <div>
                                {% if post.reading_time %}
                                    <p>{{ post.reading_time }} minute{{ post.reading_time|pluralize }}</p>
                                {% endif %}
                            </div>
                            
                            <div class='card-down-comments'>
                                <a href="{% url 'blog:post_detail' post.slug  %}#disqus_thread">No comments</a>
                            </div>

                            <div>
                                <a class="btn btn-success btn-lg card-down-button"
                                    href="{% url 'blog:post_detail' post.slug %}">Read</a>

                            </div>
                        </div>

                    </div>
                </div>
                {% endfor %}

                <!-- Pagintaion  -->
                <ul class="pagination">

                    {% if posts.has_previous %}

                    <li class="page-item"><a class="page-link"
                            href="?page=1#listing-heading">&lt;&lt;</a></li>
                    <li class="page-item"><a class="page-link"
                            href="?page={{ posts.previous_page_number }}#listing-heading">&lt;</a>
                    </li>
                    {% endif %}

                    {% for num in posts.paginator.page_range %}
                    {% if posts.number == num %}
                    <li class="page-item active"><a class="page-link"
                            href="?page={{ num }}#listing-heading">{{ num }}</a>
                    </li>
                    {% elif num > posts.number|add:'-3' and num < posts.number|add:'3' %}
                    <li class="page-item"><a class="page-link"
                            href="?page={{ num }}#listing-heading">{{ num }}</a>
                    </li>
                    {% endif %}
                    {% endfor %}

                    {% if posts.has_next %}
                    <li class="page-item"><a class="page-link"
                            href="?page={{ posts.next_page_number }}#listing-heading">&gt;</a>
                    </li>
                    <li class="page-item"><a class="page-link"
                            href="?page={{ posts.paginator.num_pages }}#listing-heading">&gt;&gt;</a>
                    </li>
                    {% endif %}
                </ul>
                <!--  -->
            </div>

            <!-- Rating Sidebar -->
            {% include 'sidebar.html' %}
        </div>
    </div>


</main>


<!-- Information Section -->
<section class="after-con">
    <div class="container">
        <h1 class="text-center font-weight-bold">How to choose the best casino
        </h1>
        <div class="row">
            <div class="col-sm">
                <img src="{% static 'img/phone_girl.png' %}"
                    alt="Girl w/ Phone">

            </div>
            <div class="col-sm">

                <p>Online Gambling Guide: How To Choose The Best Online Casino
                    In 2020 best online casino gambling sites </p>
                <p>
                    Share this entry Online gambling is booming even between
                    poker players and is becoming one of the favorite pastimes
                    of many. With every day, online casino game developers are
                    coming with ideas that are more entertaining and more
                    exciting, attracting an
                    increasing number of people to the industry. Interesting
                    games, an engaging experience, and, of course, the chance to
                    win money, are all factors that come into play. With the
                    increased popularity and demand, it is only natural for
                    the offer to grow as well. Today, the number of top online
                    casinos available on the web is probably ten times bigger
                    than what it was a few years ago – and there are new virtual
                    casinos opening their doors almost every day. With so
                    many options, how does one go about choosing the best online
                    casino site for gambling? If you aren't experienced in the
                    industry and are someone just looking to have some fun, all
                    these casinos may seem identical.
                </p>

                <h3>We provide you updates about:</h3>
                <ul>
                    <li>Free slot spins</li>
                    <li>First deposit bonuses</li>
                    <li>Free offers</li>
                    <li>Loyalty programs</li>
                    <li>Races, leaderboards, etc.</li>
                </ul>
            </div>

        </div>
    </div>
</section>

<!--  -->




<!-- After-content block  -->
<section class="inf-block">
    <div class="container">
        <h1 class="display-4 font-weight-bold">Who we are</h1>
        <p class="lead">
            We are leading resource for everything bettors, sports fans and
            gamblers want to know about the world of casinos, sports betting and
            poker. Whether it's impartial reviews of online casinos and
            sportsbooks, in-depth game or sports events guides, finding
            the best bonuses, or creating fun free games, our team of gambling
            experts work every day to keep our readers up-to-date on the topics
            that matter to them.
        </p>

        <p><img src="https://www.bettergov.org/sites/default/files/styles/story_lead/public/articles/2019/02/chicago_casino_BGA.png?itok=a-rL1MsA"
                alt="Casino Image"></p>
    </div>
</section>
<!--  -->

<script id="dsq-count-scr" src="//bestcasinos-1.disqus.com/count.js" async></script>
{% endblock %}

templates/post_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row">

        <div class="col-md-8 card mb-4  mt-4 left shadow top">
            <div class="card-body">
                <!-- Post Header -->
                <h1 class='text-cener font-weight-bold'>{% block title %}
                    {{ post.title }} {% endblock title %}</h1>
                <hr>
                <!-- Post Meta -->
                <div class="row">
                    <div class="col card-header-meta">
                        {% if post.reading_time %}
                        {{ post.reading_time }}
                        minute{{ post.reading_time|pluralize }}
                        {% endif %}
                    </div>

                    <div class="col">
                        {{ post.created_on|date:'d/m/Y H:i' }}
                    </div>

                    <div class="col card-header-meta text-right">
                        {{ post.author }}
                    </div>

                    <!-- Like Button -->
                    <div class='card-header-like-wrapper'>
                        <span id='card-header-like-count'>{{ post.like_count }}</span><span data-href='{% url "blog:post_like" post.slug %}'
                            id='card-header-like' data-post='{{ post.pk }}'></span>
                        <!-- Like -->
                    </div>
                </div>
                <!--  -->
                <!-- Post Content -->
                <p class="card-text ">{{ post.content | safe }}</p>

            </div>
        </div>

        <!-- Sidebar -->
        {% include 'sidebar.html' %}

        <!-- Disqus Comments -->
        <div class="card shadow card-comments">
            {% include 'comments.html' with slug=post.slug %}
        </div>

    </div>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.10.2/underscore-min.js" integrity="sha512-HKvDCFVKg8ZPGjecy6on7UECEpE76Y86h3GaE4JMCz+deFWdjcW/tWnh0hCfaBvURvlOa9f5CNVzt7EFkulYbw==" crossorigin="anonymous"></script>

<script>
    let debounced_post_like = _.debounce(post_like, 200)

    document.getElementById('card-header-like').addEventListener('click', debounced_post_like)

    function post_like() {
        let like_post_url = document.getElementById('card-header-like').getAttribute('data-href');
        let xhr = new XMLHttpRequest();

        xhr.open('POST', like_post_url, true);
        xhr.responseType = 'json';

        xhr.send();
        xhr.onload = function () {
            if (this.status == 200) {
                let result = this.response;

                // Change Like Count
                document.getElementById('card-header-like-count').innerText = result.like_count;

                // console.log(result)
                // console.log('works!');

            }
            else {
                // console.log('Oops something got wrong !')
            }
        }
    }
</script>
{% endblock content %}

templates/sidebar.html
{% load static %}
{% load cache %}
<link rel="stylesheet" href="{% static 'css/sidebar.css' %}">

<div class="col-md-4 float-right">

    <div class="sidebar-wrapper card shadow">
        <!-- Sidebar title -->
        <div class="my-4">
            <h5
                class="text-center bg-transparent text-uppercase font-weight-bold">
                Top 10 online casinos</h5>

            {% cache 500 top_casinos_list %}
            {% for casino in casinos %}
            <!-- Sidebar Card -->
            <div class="sidebar-card">

                <!-- Sidebar Card Image -->
                <div class="sidebar-card-image">
                    <a href="{% url 'blog:casino_detail' casino.slug %}"><img
                            src="{{ casino.image.url }}"
                            alt="{{ casino.title }}"></a>
                </div>

                <!-- Sidebar Card Body -->
                <div class="sidebar-card-body">
                    <h5>{{ casino.title }}</h5>
                    <p class="sidebar-casino-rate">
                        {{ casino.get_avg_main_rate }} 🌟</p>
                    <a href="{{ casino.link }}"
                        class="btn btn-success btn-lg">PLAY</a>
                </div>
            </div>
            <hr>
            {% endfor %}
            {% endcache %}

            <!-- Add a new casino -->
            <p class="affiliate-feedback text-center">Wanna add a new casino? <a
                    href="#">Add</a>
            </p>

            <hr>

            <!-- Sidebar footer -->
            <p>
                <a href="{% url 'blog:rating' %}"
                    class="btn btn-success btn-block text-uppercase">See all</a>
            </p>

        </div>
    </div>
</div>